1. Сгенерировать двухмерный массив arr размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида ах + b так, что после нормализации максимальный элемент массива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

arr = np.random.uniform(0, 20, (4, 7))

min_val = np.min(arr)
max_val = np.max(arr)

a = 1 / (max_val - min_val)
b = -a * min_val

arr_normalized = a * arr + b

print("Исходный массив:")
print(arr)
print("\nНормализованный массив:")
print(arr_normalized)
print("\nМинимальное значение после нормализации:", np.min(arr_normalized))
print("Максимальное значение после нормализации:", np.max(arr_normalized))


Исходный массив:
[[ 1.49828212 17.27520051 16.12947088 15.6801237   1.63624802  7.47198845
  12.81825454]
 [ 1.50544417  6.13886663  4.19384194 12.93980696  3.55376117  3.02441861
   3.63022697]
 [ 7.51555265  7.27754304  6.07732038 16.28151634  4.75785682 17.84907343
   5.70730164]
 [ 4.27872709  1.07432732  4.70276268 14.73783594 18.051814   14.40659436
   5.06194528]]

Нормализованный массив:
[[0.02497159 0.95425627 0.88677104 0.8603038  0.03309799 0.37683205
  0.69173532]
 [0.02539344 0.29830913 0.18374419 0.69889495 0.14604246 0.11486337
  0.15054641]
 [0.37939805 0.36537892 0.29468396 0.89572675 0.21696554 0.98805827
  0.27288929]
 [0.18874406 0.         0.21372041 0.80480161 1.         0.78529097
  0.23487681]]

Минимальное значение после нормализации: 0.0
Максимальное значение после нормализации: 1.0


2. Создать матрицу 8 на 10 из случайных целых (используя модуль numpy. random ) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
import numpy as np

matrix = np.random.randint(0, 11, size=(8, 10))

row_sum = np.sum(matrix, axis=1)
min_sum_row_index = np.argmin(row_sum)
min_sum_row = matrix[min_sum_row_index]

print("Индекс строки с минимальной суммой значений:", min_sum_row_index)
print("Строка с минимальной суммой значений:", min_sum_row)

Индекс строки с минимальной суммой значений: 6
Строка с минимальной суммой значений: [2 7 2 0 2 1 8 8 3 8]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

distance = np.sqrt(np.sum((vector1 - vector2)**2))

print("Евклидово расстояние между векторами:", distance)

Евклидово расстояние между векторами: 5.196152422706632


4. Решить матричное уравнение АХВ=-С - найти матрицу Х. Где А = [-1, 2, 4], [-3, 1, 2], [-3, 0, 1]], В=[[3, -1], [2, 1]], С=[[7, 21], [11, 8], [8, 4]]

In [6]:
import numpy as np

A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

X = np.dot(np.dot(A_inv, -C), B_inv)

print("Матрица X:")
print(X)


Матрица X:
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


Лабораторная работа №1

1.  Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.

In [8]:
import numpy as np

data = np.loadtxt("minutes_n_ingredients.csv", delimiter=";", skiprows=1, dtype=np.int32)

print(data[:5])

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]
 [152828     40      7]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [9]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

mean_values = np.mean(data, axis=0)

min_values = np.min(data, axis=0)

max_values = np.max(data, axis=0)

median_values = np.median(data, axis=0)

print("Среднее значение по столбцам:")
print(mean_values)
print("\nМинимум по столбцам:")
print(min_values)
print("\nМаксимум по столбцам:")
print(max_values)
print("\nМедиана по столбцам:")
print(median_values)

Среднее значение по столбцам:
[2.22065272e+05 2.16012171e+04 9.05521055e+00]

Минимум по столбцам:
[38.  0.  1.]

Максимум по столбцам:
[5.37671000e+05 2.14748365e+09 3.90000000e+01]

Медиана по столбцам:
[2.07196e+05 4.00000e+01 9.00000e+00]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля q0.75.

In [10]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

minutes = data[:, 1]

q75 = np.quantile(minutes, 0.75)

minutes_limited = np.minimum(minutes, q75)

print("Квантиль q0.75:", q75)
print("Продолжительность выполнения рецептов после ограничения:")
print(minutes_limited)

Квантиль q0.75: 65.0
Продолжительность выполнения рецептов после ограничения:
[25. 10.  5. ... 65.  5. 65.]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [12]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

minutes = data[:, 1]

zero_duration_count = np.count_nonzero(minutes == 0)

minutes[minutes == 0] = 1

print("Количество рецептов с продолжительностью выполнения, равной нулю:", zero_duration_count)
print("Продолжительность выполнения рецептов после замены:")
print(minutes)

Количество рецептов с продолжительностью выполнения, равной нулю: 479
Продолжительность выполнения рецептов после замены:
[ 25.  10.   5. ...  65.   5. 140.]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [14]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

recipe_ids = data[:, 0]

unique_recipe_count = len(np.unique(recipe_ids))

print("Количество уникальных рецептов в датасете:", unique_recipe_count)


Количество уникальных рецептов в датасете: 99999


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [16]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

ingredient_counts = data[:, 2]

unique_ingredient_counts, counts = np.unique(ingredient_counts, return_counts=True)

print("Различные значения количества ингредиентов в рецептах:")
for count, freq in zip(unique_ingredient_counts, counts):
    print(f"{int(count)} ингредиентов: {freq} рецептов")


Различные значения количества ингредиентов в рецептах:
1 ингредиентов: 13 рецептов
2 ингредиентов: 926 рецептов
3 ингредиентов: 2895 рецептов
4 ингредиентов: 5515 рецептов
5 ингредиентов: 7913 рецептов
6 ингредиентов: 9376 рецептов
7 ингредиентов: 10628 рецептов
8 ингредиентов: 10951 рецептов
9 ингредиентов: 10585 рецептов
10 ингредиентов: 9591 рецептов
11 ингредиентов: 8297 рецептов
12 ингредиентов: 6605 рецептов
13 ингредиентов: 4997 рецептов
14 ингредиентов: 3663 рецептов
15 ингредиентов: 2595 рецептов
16 ингредиентов: 1766 рецептов
17 ингредиентов: 1246 рецептов
18 ингредиентов: 790 рецептов
19 ингредиентов: 573 рецептов
20 ингредиентов: 376 рецептов
21 ингредиентов: 217 рецептов
22 ингредиентов: 161 рецептов
23 ингредиентов: 105 рецептов
24 ингредиентов: 69 рецептов
25 ингредиентов: 50 рецептов
26 ингредиентов: 28 рецептов
27 ингредиентов: 16 рецептов
28 ингредиентов: 16 рецептов
29 ингредиентов: 12 рецептов
30 ингредиентов: 12 рецептов
31 ингредиентов: 3 рецептов
32 ингредиентов:

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [15]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

ingredient_counts = data[:, 2]

filtered_data = data[ingredient_counts <= 5]

print("Первые 5 строк данных для рецептов с не более чем 5 ингредиентами:")
print(filtered_data[:5])

Первые 5 строк данных для рецептов с не более чем 5 ингредиентами:
[[4.46597e+05 1.50000e+01 5.00000e+00]
 [2.04134e+05 5.00000e+00 3.00000e+00]
 [2.56230e+04 6.00000e+00 4.00000e+00]
 [4.84223e+05 1.80000e+01 4.00000e+00]
 [6.31500e+04 2.50000e+02 4.00000e+00]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [17]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

times = data[:, 1]
ingredient_counts = data[:, 2]

average_ingredients_per_minute = ingredient_counts / times

max_average_ingredients_per_minute = np.max(average_ingredients_per_minute)

print(f"Максимальное среднее количество ингредиентов на одну минуту: {max_average_ingredients_per_minute}")

Максимальное среднее количество ингредиентов на одну минуту: inf


C:\Users\233490\AppData\Local\Temp\ipykernel_13100\3948787432.py:8: RuntimeWarning: divide by zero encountered in divide
  average_ingredients_per_minute = ingredient_counts / times


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [18]:
import numpy as np

data = np.genfromtxt('minutes_n_ingredients.csv', delimiter=';', skip_header=1)

sorted_data = data[data[:, 1].argsort()][::-1]

top_100_data = sorted_data[:100]

ingredient_counts_top_100 = top_100_data[:, 2]

average_ingredient_count_top_100 = np.mean(ingredient_counts_top_100)

print(f"Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: {average_ingredient_count_top_100}")

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 6.63


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [20]:
import numpy as np
import pandas as pd

data = pd.read_csv('minutes_n_ingredients.csv')

num_recipes = len(data)

random_indices = np.random.choice(num_recipes, 10, replace=False)

selected_recipes = data.iloc[random_indices]
print(selected_recipes)


        127244;60;16
92519    288706;46;5
36784   201561;70;10
14724  315030;145;10
6278     70696;60;12
53902     36091;5;10
63364    88198;255;3
70237     95620;25;7
47776    344342;70;5
99182     21011;45;6
61526     93147;50;6


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [29]:
import numpy as np 
recep = np.loadtxt("minutes_n_ingredients.csv", skiprows=1, dtype="int32", delimiter=";")
print(f"процент рецептов, кол-во ингредиентов в которых меньше среднего = {np.mean(recep[:, 2] < np.mean(recep[:, 2])) * 100}%")

процент рецептов, кол-во ингредиентов в которых меньше среднего = 58.802588025880254%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.


In [30]:
simple = ((arr2[:, 1] <= 20) & (arr2[:, 2] <= 5))
print(simple)
print(simple.astype(int), end='\n\n')

new_arr2 = np.column_stack((arr2, simple))
print(new_arr2)

NameError: name 'arr2' is not defined

13. Выведите процент "простых" рецептов в датасете

In [31]:
simple_recept_count = np.sum(simple_recept)
procent_simple_recept = (simple_recept_count / len(file)) * 100
print(f"Процент простых рецептов в датасете: {procent_simple_recept}%")

NameError: name 'simple_recept' is not defined

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут: стандартными, если их продолжительность составляет более 10, но менее 20 минут, и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.